version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: postgres
    environment:
        POSTGRES_USER: myshop
        POSTGRES_PASSWORD: qazwsxedc
        POSTGRES_DB: shop2go
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: xxx@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    ports:
        - "5050:80"
    links:
      - "db:pgsql-server"


