import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
//import { signIn, signOut, useSession } from "next-auth/react";
//import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import { useForm, SubmitHandler } from "react-hook-form";
import { trpc } from "../../utils/trpc";
import Navbar2 from "../../components/navbar";
import { z } from "zod";


const EditProduct: NextPage = () => {
  const createProduct = trpc.product.create.useMutation({
    async onSuccess() {
      console.log("onSuccess");
    },
  });
  return (
    <>
      <Head>
        <title>Go2Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar2/>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]"> Product </h1>


          <form className="flex flex-col items-center gap-2"
                onSubmit={async (e) => {

                  e.preventDefault();
                  const $form = e.currentTarget;
                  const values = Object.fromEntries(new FormData($form));
                  //type Input = inferProcedureInput<AppRouter['user']['updateData']>;
                  const input= {
                    productName:values.productName as string,
                    productImage:values.productImage as string,
                    productPrice:Number(values.productPrice) as number,
                    productCreatedBy:1,
                    productCategory:1
                  };
                  try {
                    await createProduct.mutateAsync(input);

                    //$form.reset();
                  } catch (cause) {
                    console.error({ cause }, 'Failed to add post');
                  }
                }}
          >
            <label className="text-2xl text-white">Product Name</label>
            <input className="rounded-xl bg-white/10 p-4 text-white" type="text" placeholder="Name" name={"productName"} />
            <label className="text-2xl text-white">Image Url</label>
            <input className="rounded-xl bg-white/10 p-4 text-white" type="text" placeholder={"http://google.com"} name={"productImage"} />
            <label className="text-2xl text-white">Product Price</label>
            <input className="rounded-xl bg-white/10 p-4 text-white" type="text" placeholder="100" name={"productPrice"}  />
            <button type={"submit"} className={ "rounded-xl bg-white/10 p-4 text-white"}   >Save</button>
          </form>
        </div>
      </main>
    </>
  );
};

export default EditProduct;

