import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
//import { signIn, signOut, useSession } from "next-auth/react";
//import {serverSideTranslations} from "next-i18next/serverSideTranslations";

import { trpc } from "../../utils/trpc";

const Profile: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Go2Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T4</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>

          </div>
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]"> Profile </h1>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
          </div>

          <form className="flex flex-col items-center gap-2">
            <label className="text-2xl text-white">Name</label>
            <input className="rounded-xl bg-white/10 p-4 text-white" type="text" placeholder="Name" defaultValue={hello.data ? hello.data.greeting : "Loading"} />
            <label className="text-2xl text-white">Upload Image</label>
            <input className="rounded-xl bg-white/10 p-4 text-white" type="file" />
            <label className="text-2xl text-white">Email</label>
            <input className="rounded-xl bg-white/10 p-4 text-white" type="text" placeholder="Email" defaultValue={hello.data ? hello.data.greeting : "Loading"} />
            <label className="text-2xl text-white">Phone</label>
            <input className="rounded-xl bg-white/10 p-4 text-white" type="text" placeholder="Phone" defaultValue={hello.data ? hello.data.greeting : "Loading"} />
            <label className="text-2xl text-white">Address</label>
            <input className="rounded-xl bg-white/10 p-4 text-white" type="text" placeholder="Address" name={"Address"} defaultValue={hello.data ? hello.data.greeting : "Loading"} />
          </form>

        </div>
      </main>
    </>
  );
};

export default Profile;

